//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detalleboleta
    {
        public int id { get; set; }
        public Nullable<int> idpedido { get; set; }
        public Nullable<decimal> montifinal { get; set; }
        public Nullable<int> idmodopago { get; set; }
        public string observacion { get; set; }
        public Nullable<int> idempleado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual modopago modopago { get; set; }
        public virtual pedido pedido { get; set; }
    }
}
