//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class restaurantEntities : DbContext
    {
        public restaurantEntities()
            : base("name=restaurantEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tipoproducto> tipoproducto { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<promocion> promocion { get; set; }
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<detalleboleta> detalleboleta { get; set; }
        public virtual DbSet<empleado> empleado { get; set; }
        public virtual DbSet<modopago> modopago { get; set; }
        public virtual DbSet<productopedido> productopedido { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<modulo> modulo { get; set; }
        public virtual DbSet<operaciones> operaciones { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<rol_operacion> rol_operacion { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual ObjectResult<Returnproducto_Result> Returnproducto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Returnproducto_Result>("Returnproducto");
        }
    
        public virtual ObjectResult<ventas_Result> ventas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ventas_Result>("ventas");
        }
    }
}
