//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class promocion
    {
        public int id { get; set; }
        public Nullable<int> idproducto { get; set; }
        public Nullable<decimal> nuevoprecio { get; set; }
        public Nullable<int> cantidad { get; set; }
        public string titulo { get; set; }
        public string img { get; set; }
        public string descripPromo { get; set; }
    
        public virtual producto producto { get; set; }
    }
}
